### PR TITLE
Update ImageProcessorCore to ImageSharp

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
Thanks for submitting a PR! :clap:

Please make sure you have selected the correct section and try to include all information for the table (if available).

Aim to use [consistent terminology](https://github.com/jpsingleton/ANCLAFS/issues/7) for status ( **Yes** / **No** / **WIP** / **?** / **{blank}** ) and a bare hyperlink style (no protocol).

Cheers :beers:

:shipit:

### CODE REVIEW

**Comment by jpsingleton** [comment]
Awesome thanks @JimBobSquarePants! Should the MyGet link point to https://www.myget.org/gallery/imagesharp instead of https://www.myget.org/gallery/imageprocessor now?

**Comment by JimBobSquarePants** [comment]
Oops!

Yes, it most certainly should... I'm working on getting API docs up and running over the next few weeks so I'll have a proper url to add then also. Thanks for sharing my work 😄

**Comment by jpsingleton** [comment]
OK, I'll fix it up and push it live. No problem, I think .NET Core will really take off if enough package maintainers get on board. Especially now that v1.1 is out and things have stabilised more.

**Comment by JimBobSquarePants** [comment]
Thanks... Yeah I agree. Really looking forward to being able to develop confidently x-plat!

**Pull request merged**
