### PR TITLE
Include LibGit2Sharp

### PR DESCRIPTION
**Pull request by ethomson**
Include the LibGit2Sharp library, which is a .NET Core and .NET Framework compatible wrapper on top of the native libgit2 library.

### CODE REVIEW

**Comment by jpsingleton** [comment]
Great. Thanks @ethomson.
Please let me know when it's stable and supports net standard 2.

**Comment by ethomson** [comment]
Thanks @jpsingleton!  .NET Standard 2 coming soon.

**Comment by ethomson** [comment]
[LibGit2Sharp v0.25](https://github.com/libgit2/libgit2sharp/releases/tag/v0.25) now supports .NET Standard 2.

**Comment by jpsingleton** [comment]
Updated, thanks.

**Pull request merged**
